apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

