package com.benjamin.Banking_app.Transactions;

public enum TransactionType {
    WITHDRAW,
    DEPOSIT,
    TRANSFER_OUT,
    TRANSFER_IN,

    LOAN_REPAYMENT,
    FULL_LOAN_REPAYMENT,
    LOAN_APPLICATION,

    DIRECT_DEBIT_CREATED,
    DIRECT_DEBIT_PAID,
    DIRECT_DEBIT_RECEIVED,
    DIRECT_DEBIT_UPDATED,
    DIRECT_DEBIT_CANCELLED
}
